cleaned up code
git-svn-id: https://tweety.arinola.net/svn/trunk@20 af43ea2c-c91c-496b-bf95-934215697a66

diff --git a/samples/misc/mp3toau b/samples/misc/mp3toau
--- a/samples/misc/mp3toau
+++ b/samples/misc/mp3toau
@@ -1,8 +1,33 @@
 #!/bin/sh
 
+# mp3toau
+# Vino Crescini
+# 20 June 2001
+
+mpgprog="/usr/bin/mpg123"
 count=0
+
+if ! [ ${#} = "1" ]
+then
+  echo "${0} <destination dir>"
+  exit 0
+fi
+
+if ! [ -d ${1} ] || ! [ -w ${1} ]
+then
+  echo "${1} does not exist / not writable"
+  exit 0
+fi
+
+if ! [ -x ${mpgprog} ]
+then
+  echo "can't find ${mpgprog}"
+  exit 0
+fi
 
 find . -name "*.mp3" | while read filename
 do
-  echo about to convert ${filename} to $[count++].au
+  count=$[$count + 1]
+  echo ${filename} -> ${1}/${count}.au
+  ${mpgprog} -sq "${filename}" > ${1}/${count}.au
 done
